package gui;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.concurrent.Task;
import javafx.scene.Scene;
import javafx.scene.control.TextArea;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

public class Task4GUI extends Application {

    private TextArea textArea;
    // Specify the path to the output file generated by the task2 package
    private final String outputFilePath = "output/Task4/part-r-00000";

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Task 4 - Mean, Medium Thrusting Points Per Channel");

        textArea = new TextArea();
        textArea.setEditable(false);

        VBox vbox = new VBox(textArea);
        Scene scene = new Scene(vbox, 600, 400);
        primaryStage.setScene(scene);
        primaryStage.show();

        // Automatically load the output file when the GUI is opened
        loadDataInBackground(new File(outputFilePath));
    }

    private void loadDataInBackground(File file) {
        Task<Void> task = new Task<Void>() {
            @Override
            protected Void call() throws Exception {
                try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                    String line;
                    StringBuilder sb = new StringBuilder();
                    while ((line = br.readLine()) != null) {
                        sb.append(line).append("\n");
                        if (isCancelled()) {
                            break;
                        }
                    }
                    Platform.runLater(() -> textArea.setText(sb.toString()));
                } catch (IOException e) {
                    e.printStackTrace();
                }
                return null;
            }
        };
        new Thread(task).start();
    }

    public static void main(String[] args) {
        launch(args);
    }
}